#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

source "$PLUGIN_DIR/colors.sh"

# Bar style
bar=(
  position=top
  height=32
  blur_radius=32
  sticky=on
  color="$BAR_COLOR"
  )
sketchybar --bar "${bar[@]}"

default=(
  background.color="$ITEM_BG_COLOR"
  background.corner_radius=10
  background.height=28
  background.y_offset=0
  background.padding_left=10
  background.padding_right=10
  background.y_offset=1
  padding_left=5
  padding_right=5
  icon.font="JetBrainsMono Nerd Font:Light:15.0"
  label.font="JetBrainsMono Nerd Font:Light:13.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=0
  icon.padding_right=0
  label.padding_left=8
  label.padding_right=8
  icon.y_offset=1
  label.y_offset=1
)
sketchybar --default "${default[@]}"

# Mission Control space indicators
SPACE_ICONS=("1" "2" "3" "4")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=8
    icon.padding_right=8
    icon.y_offset=1
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

# Right side items
source "$ITEMS_DIR/calendar.sh"
source "$ITEMS_DIR/battery.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
