#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

source "$PLUGIN_DIR/colors.sh"

# Bar style
bar=(
  position=top
  height=33
  blur_radius=32
  sticky=on
  margin=0
  color="$BAR_COLOR"
  )
sketchybar --bar "${bar[@]}"

default=(
  background.color="$ITEM_BG_COLOR"
  background.corner_radius=5
  background.height=30
  background.padding_left=5
  background.padding_right=5
  padding_left=5
  padding_right=5
  # icon.font="JetBrainsMono Nerd Font:Light:16.0"
  # label.font="JetBrainsMono Nerd Font:Light:15.0"
  icon.font="CommitMono:Regular:15.0"
  label.font="CommitMono:Regular:15.0"
  icon.color="$FG_COLOR"
  label.color="$FG_COLOR"
  icon.padding_left=2
  icon.padding_right=2
  label.padding_left=5
  label.padding_right=5
  icon.y_offset=0
  label.y_offset=0
)
sketchybar --default "${default[@]}"

# Left side
source "$ITEMS_DIR/space.sh"

# Right side
source "$ITEMS_DIR/clock.sh"
source "$ITEMS_DIR/calendar.sh"
source "$ITEMS_DIR/battery.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
